### ISSUE TITLE
Bot gets another request

### ISSUE THREAD

**Issue by ChehST** [ChehST/tg-auto-sales#12]
bot crushes with the error

```
2024-12-28 11:38:49,982 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.

Traceback (most recent call last):

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/ext/_updater.py", line 750, in _network_loop_retry

    if not await do_action():

           ^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/ext/_updater.py", line 744, in do_action

    return action_cb_task.result()

           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/ext/_updater.py", line 371, in polling_action_cb

    updates = await self.bot.get_updates(

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 650, in get_updates

    updates = await super().get_updates(

              ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/_bot.py", line 4480, in get_updates

    await self._post(

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/_bot.py", line 619, in _post

    return await self._do_post(

           ^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 354, in _do_post

    return await super()._do_post(

           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/_bot.py", line 648, in _do_post

    result = await request.post(

             ^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 202, in post

    result = await self._request_wrapper(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/tg-auto-sales/venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 385, in _request_wrapper

    raise Conflict(message)

telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
```

**Comment by ChehST** [comment]
Так происходит потому что запущенно несколько приложений, которые стучатся по одному токену. По моей невнимательности у меня был запущен контейнер на локальной тачке. Closes
